### ISSUE TITLE
Implementation Choices

### ISSUE THREAD

**Issue by dbeach24** [iamed2/ResultTypes.jl#2]
I found this project after implementing my own Result type in Julia.  I'm opening this issue just as a way to compare ideas.

Our implementations are strikingly similar, with a few interesting differences:
1. In my implementation, `Result` is immutable.  I assume this is more efficient since it allows for stack allocation.
2. This `Result` uses two `Nullable` fields to implement the Alternative monad pattern.  I cheaped out in my implementation and relied on leaving the value field uninitialized in the case where there is no value.  (This allows me to save a few bytes of storage in the type.)
3. This implementation (properly) stores actual exceptions for the error case; mine just uses a `Symbol`.  I reasoned that `Symbol` would have very low storage overhead, while still providing some way to differentiate between error causes.  (I use `:ok` to indicate the lack of error, in which case the second field `value::T` is defined.)

For comparison, this is what my Result definition looks like:

``` jl
immutable Result{T}
    err::Symbol
    value::T
    Result{T}(err::Symbol, value::T) = new(err, value)
    Result(err::Symbol) = new(err)
end

ok(value) = Result{typeof(value)}(:ok, value)
fail{T}(err::Symbol, ::Type{T}) = Result{T}(err)
```

I particularly like your use of conversion to "automatically" wrap the raw result with the `Result` type.  (Weirdly, this seems to incur a 12% penalty when compared with constructing the `Result` directly at each `return` point... but that is a pretty small overhead, given that function itself is merely integer division!)

Anyhow, I'd be interested in any thoughts you have regarding 1-3 above.  Thanks!

**Comment by PallHaraldsson** [comment]
I see there are implementation choices, but I didn't look much into, only see this package now also use immutable.

For either you or @iamed2, I'm more curious about, not your implementation choices, but rather Julia users have the choice of using Result types (or just exceptions). I'm first now seeing the package, and it seems like inspired by Go error code approach.

The good thing I see with this, is that people have a choice (some dislike exceptions, rightly or wrongly) and that it's faster, but do Julia's exceptions need to be slower (or in any way worse)?

http://joeduffyblog.com/2016/02/07/the-error-model/

"In summary, the exceptions approach was 7% smaller and 4% faster as a geomean across our key benchmarks, thanks to a few things:"

[Before advocating, this/package approach over the language default, I would like to know pros and cons, of the default (vs. an optimal implementation of exceptions as the language specifies or with changes to syntax/semantics if need be).]

See the table with:

"Wouldn’t it be great if we could take all of The Goods and leave out The Bads and The Uglies?"

below.

This article is interesting and even more general with e.g.:

"Saying an unintended arithmetic over/underflow represents a bug is certainly a contentious stance. In an unsafe system, however, such things frequently lead to security vulnerabilities. I encourage you to review the National Vulnerability Database to see the sheer number of these. [link]

In fact, the Windows TrueType Font parser, which we ported to Midori (with gains in performance), has suffered over a dozen of them in the past few years alone. (Parsers tend to be farms for security holes like this.)

This has given rise to packages like SafeInt, which essentially moves you away from your native language’s arithmetic operations, in favor of checked library ones."

--

[Another thing, this code should work on all platforms (as this code, and all pure Julia code (w/o ccall) should(?); I just saw osx testing dropped, I assume since just redundant.]

**Comment by iamed2** [comment]
Disclaimer: I only had time to skim the article you posted.

> The good thing I see with this, is that people have a choice (some dislike exceptions, rightly or wrongly) and that it's faster, but do Julia's exceptions need to be slower (or in any way worse)?

I discuss some performance issues with exceptions in my talk: https://www.youtube.com/watch?v=riDHvRXnxeg

Mainly, if you want a backtrace you will incur additional costs. I don't believe there is an inherent blocker to non-erroring code using exceptions being exactly as fast as using Result, but it would require some additional attention. 

The main reason they were able to overcome this AFAICT was this:
> - All throwing functions were known in the type system, enabling more flexible code motion.
> - All throwing functions were known in the type system, giving us novel EH optimizations, like turning try/finally blocks into straightline code when the try could not throw.

If Julia had this approach, it could achieve the same results, but I think that is very unlikely in the 1.0 timeline at least.

Lastly, I would say it's not a good idea to stick religiously to either approach in a Julia program. Result is good for a particular set of cases where you 1) know which errors you want to pass up and which you want to handle 2) you need speed and 3) you don't care about backtraces, and I myself don't often use it. 

--

Yep, just dropped because it was redundant. This will work everywhere.

**Comment by kmsquire** [comment]
Can probably be closed...
